[project]
name = "modded-nanogpt-rwkv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "huggingface-hub>=0.26.1",
    "numpy>=2.1.2",
    "tinygrad>=0.9.2",
    "tqdm>=4.66.5",
]
